# Generated by Django 5.1.2 on 2024-10-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='banner_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='cover_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
