# Generated by Django 5.1.2 on 2024-10-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0001_initial'),
        ('donation', '0002_alter_cause_banner_image_alter_cause_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cause',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cause.cause'),
        ),
        migrations.DeleteModel(
            name='Cause',
        ),
    ]
