# Generated by Django 5.1.2 on 2024-10-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tagline', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(upload_to='images/')),
                ('cover_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
