# Generated by Django 5.1.2 on 2024-11-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cause', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
